apiVersion: v1
kind: Service
metadata:
   name: {{ .Values.kibana.name }}
spec:
   selector:
      app: {{ .Values.kibana.name }}
   ports:
      - protocol: TCP
        port: 5601
        targetPort: 5601
