apiVersion: batch/v1beta1
kind: CronJob
metadata:
   name: {{.Values.elasticsearch.name}}-backup
spec:
   schedule: { { .Values.backup.schedule } }
   jobTemplate:
      spec:
         template:
            spec:
               containers:
                  - name: elasticsearch-backup
                    image: { { .Values.backup.image } }
                    env:
                       - name: ELASTICSEARCH_URL
                         value: http://elasticsearch:9200
                       - name: SNAPSHOT_REPO
                         value: { { .Values.backup.repository } }
